/**
 * The visual hook is stamped by ffmpeg, not generated by Kling. A video model
 * blends frames, so it cannot land a disruption on one frame and cut it on the
 * next. ffmpeg can. Every hook covers the whole picture, then is gone.
 *
 * The look (glitch, bars, invert, and the rest) is chosen earlier. The timing
 * is chosen when the hook is about to be stamped, one of three patterns, each
 * with an equal chance. Even spans are on. Odd spans are off.
 *   double  0.5s: on 0.2, off 0.1, on 0.2
 *   strobe  0.5s: on 0.1, off 0.1, on 0.1, off 0.1, on 0.1
 *   tail    0.6s: on 0.1, off 0.1, on 0.1, off 0.1, on 0.2
 */
export const HOOKS = ['glitch', 'color_bars', 'invert', 'vhs', 'thermal', 'blue_screen'] as const;
export type Hook = (typeof HOOKS)[number];

export const HOOK_TIMINGS = {
  double: [0.2, 0.1, 0.2],
  strobe: [0.1, 0.1, 0.1, 0.1, 0.1],
  tail: [0.1, 0.1, 0.1, 0.1, 0.2],
} as const;
export const HOOK_TIMING_IDS = ['double', 'strobe', 'tail'] as const;
export type HookTiming = (typeof HOOK_TIMING_IDS)[number];

/** The original window. Timing patterns carry their own length. */
export const HOOK_SECONDS = 0.5;

export function isHook(value: string): value is Hook {
  return (HOOKS as readonly string[]).includes(value);
}

/** Equal chance for each pattern. `random` is injectable for tests. */
export function pickHookTiming(random: () => number = Math.random): HookTiming {
  const index = Math.floor(random() * HOOK_TIMING_IDS.length);
  return HOOK_TIMING_IDS[Math.min(index, HOOK_TIMING_IDS.length - 1)];
}

/** Frame counts for each on/off span. They sum to the pattern's window. */
export function timingSpanFrames(timing: HookTiming, fps: number): number[] {
  let cursor = 0;
  return HOOK_TIMINGS[timing].map((span) => {
    const next = cursor + span * fps;
    const count = Math.round(next) - Math.round(cursor);
    cursor = next;
    return count;
  });
}

export function hookFrames(fps: number, timing: HookTiming = 'double'): number {
  return Math.max(1, timingSpanFrames(timing, fps).reduce((sum, count) => sum + count, 0));
}

export type ClipShape = { width: number; height: number; fps: number };

/** Inclusive frame ranges where the hook is on. Even spans are on. */
export function timingOnRanges(timing: HookTiming, fps: number): Array<[number, number]> {
  const ranges: Array<[number, number]> = [];
  let cursor = 0;
  timingSpanFrames(timing, fps).forEach((count, index) => {
    if (index % 2 === 0 && count > 0) ranges.push([cursor, cursor + count - 1]);
    cursor += count;
  });
  return ranges;
}

function hookEnable(timing: HookTiming, fps: number): string {
  return timingOnRanges(timing, fps)
    .map(([start, end]) => `between(n\\,${start}\\,${end})`)
    .join('+');
}

/**
 * One filtergraph chain from `[0:v]` to `[bg]`. `on` is the chosen timing.
 */
export function hookFilter(hook: Hook, clip: ClipShape, timing: HookTiming = 'double'): string {
  const frames = hookFrames(clip.fps, timing);
  const on = hookEnable(timing, clip.fps);
  const size = `${clip.width}x${clip.height}`;
  const rate = clip.fps;

  switch (hook) {
    case 'glitch': {
      const band = 'floor(Y*18/H+floor(N/3)*7)';
      const tear = `gt(abs(sin(${band}*12.9898+N*78.233))\\,0.45)`;
      const shift = `${tear}*sin(${band}*4.13+N*9.7)*W*0.18`;
      const flip = `gt(sin(${band}*7.77+N*3.1)\\,0.8)`;
      const px = (c: 'r' | 'g' | 'b') =>
        `if(${flip}\\,255-${c}(X+${shift}\\,Y)\\,${c}(X+${shift}\\,Y))`;
      const split = Math.round(clip.width * 0.025);
      return [
        `[0:v]format=gbrp`,
        `geq=r='${px('r')}':g='${px('g')}':b='${px('b')}':enable='${on}'`,
        `rgbashift=rh=-${split}:bh=${split}:enable='${on}'`,
        `eq=contrast=1.6:brightness=0.12:enable='${on}'`,
        `noise=alls=40:allf=t:enable='${on}'`,
        `format=yuv420p[bg]`,
      ].join(',');
    }
    case 'color_bars':
      return [
        `smptehdbars=s=${size}:r=${rate}:d=1,format=yuv420p,noise=c0s=45:c0f=t+u[bars]`,
        `[0:v][bars]overlay=0:0:enable='${on}':eof_action=pass,format=yuv420p[bg]`,
      ].join(';');
    case 'invert':
      return `[0:v]format=yuv420p,negate=enable='${on}'[bg]`;
    case 'vhs': {
      const band = `(0.95-0.9*N/${frames})`;
      const inBand = `between(Y/H\\,${band}\\,${band}+0.12)`;
      const tear = `between(Y/H\\,${band}-0.06\\,${band})*W*0.06`;
      const wobble = `(W*0.008*sin(Y*0.09+N*2.3)+${tear})`;
      const lines = '(0.62+0.38*mod(floor(Y/3)\\,2))';
      return [
        `[0:v]format=yuv420p`,
        `eq=brightness=0.2:contrast=0.65:saturation=0.45:enable='${on}'`,
        `geq=lum='if(${inBand}\\,150+105*random(1)\\,lum(X+${wobble}\\,Y)*${lines})':cb='if(${inBand}\\,128\\,cb(X+${wobble}+3\\,Y))':cr='if(${inBand}\\,128\\,cr(X+${wobble}-3\\,Y))':enable='${on}'`,
        `noise=alls=22:allf=t:enable='${on}'`,
        `format=yuv420p[bg]`,
      ].join(',');
    }
    case 'thermal':
      return [
        `[0:v]format=yuv420p`,
        `hue=s=0:enable='${on}'`,
        `eq=gamma=2.8:contrast=1.15:enable='${on}'`,
        `format=gbrp`,
        `curves=r='0/0 0.3/0.05 0.55/0.9 0.8/1 1/1':g='0/0 0.4/0 0.65/0.45 0.85/0.95 1/1':b='0/0.3 0.22/0.9 0.45/0.55 0.6/0 1/0.85':enable='${on}'`,
        `noise=alls=10:allf=t:enable='${on}'`,
        `format=yuv420p[bg]`,
      ].join(',');
    case 'blue_screen':
      return [
        `color=c=0x0a1ec8:s=${size}:r=${rate}:d=1,format=yuv420p,geq=lum='lum(X\\,Y)*(0.82+0.18*mod(floor(Y/2)\\,2))':cb='cb(X\\,Y)':cr='cr(X\\,Y)',noise=c0s=10:c0f=t+u[blue]`,
        `[0:v][blue]overlay=0:0:enable='${on}':eof_action=pass,format=yuv420p[bg]`,
      ].join(';');
  }
}
