/**
 * Freeze the spec's framework and bucket text and the humanizer skill into
 * lib/reels/copy/source-text.generated.ts. The worker deploy excludes
 * `.cursor/`, so the writer prompt cannot read the skill file on the VM.
 *
 *   npm run reels:sync-copy-text
 *
 * Changing either source changes the writer prompt: bump
 * COPY_PROMPT_VERSION and get the new wording approved (R6).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import {
  HUMANIZER_PATH,
  SPEC_PATH,
  extractBuckets,
  extractFrameworks,
  extractHumanizer,
} from '@/lib/reels/copy/extract';

const root = path.resolve(__dirname, '..');
const spec = readFileSync(path.join(root, SPEC_PATH), 'utf8');
const humanizer = readFileSync(path.join(root, HUMANIZER_PATH), 'utf8');

const out = [
  '// Generated by scripts/reels_sync_copy_text.ts. Do not edit by hand.',
  `// Sources: ${SPEC_PATH} and ${HUMANIZER_PATH}.`,
  '',
  "import type { BucketId, FrameworkId } from '@/lib/reels/scoring/decide';",
  "import type { SpecSection } from '@/lib/reels/copy/extract';",
  '',
  `export const HUMANIZER_TEXT = ${JSON.stringify(extractHumanizer(humanizer))};`,
  '',
  `export const FRAMEWORK_SPEC_TEXT: Record<FrameworkId, SpecSection> = ${JSON.stringify(extractFrameworks(spec), null, 2)};`,
  '',
  `export const BUCKET_SPEC_TEXT: Record<BucketId, SpecSection> = ${JSON.stringify(extractBuckets(spec), null, 2)};`,
  '',
].join('\n');

const target = path.join(root, 'lib/reels/copy/source-text.generated.ts');
writeFileSync(target, out);
console.log(`Wrote ${path.relative(root, target)}`);
