/**
 * Freeze the humanizer skill into lib/stories/copy/humanizer.generated.ts
 * (S-17, S-21). The worker may run where `.cursor/` isn't shipped.
 *
 *   npm run stories:sync-copy-text
 *
 * A change here changes every Stories writing prompt: bump their versions
 * and get the wording approved.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { HUMANIZER_PATH, extractHumanizer } from '@/lib/reels/copy/extract';

const root = process.cwd();
const text = extractHumanizer(readFileSync(path.join(root, HUMANIZER_PATH), 'utf8'));
const target = path.join(root, 'lib/stories/copy/humanizer.generated.ts');
writeFileSync(target, ['// Generated by scripts/stories_sync_copy_text.ts. Do not edit by hand.', `// Source: ${HUMANIZER_PATH}.`, '', `export const HUMANIZER_TEXT = ${JSON.stringify(text)};`, ''].join('\n'));
console.log(`Wrote ${path.relative(root, target)}`);
